spring:
  application:
    name: gateway-service
  cloud:
    polaris:
      address: 127.0.0.1:8091
    gateway:
      routes:
        - id: vehicle-service
          uri: lb://vehicle-service
          predicates:
            - Path=/api/vehicles/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: alert-service
          uri: lb://alert-service
          predicates:
            - Path=/api/alerts/**
server:
  port: 8080
